// Generated by CoffeeScript 1.3.3
(function() {
  var Builder, child_process;

  child_process = require('child_process');

  Builder = (function() {

    function Builder(makefile_path) {
      this.makefile_path = makefile_path;
    }

    Builder.prototype.build = function(target, success, failure) {
      var error_msg, make_argv, make_process;
      make_argv = ['-f', this.makefile_path, target];
      make_process = child_process.spawn('make', make_argv);
      error_msg = "";
      make_process.stderr.on("data", function(data) {
        return error_msg += data.toString();
      });
      return make_process.on('exit', function(code) {
        console.log("Exiting with code ", code);
        if (code === 0) {
          return success(target);
        } else {
          console.log(error_msg);
          return failure(error_msg);
        }
      });
    };

    return Builder;

  })();

  module.exports = Builder;

}).call(this);
