// Generated by CoffeeScript 1.3.3
(function() {
  var ASSET_PATH, Builder, ENVIRONMENT, NODE_BIN_PATH, child_process, extend, growl, path, _ref,
    __slice = [].slice;

  child_process = require('child_process');

  path = require('path');

  growl = require('growl');

  NODE_BIN_PATH = "./node_modules/.bin/";

  extend = function() {
    var c, k, obj, objs, v, _i, _len;
    c = arguments[0], objs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = objs.length; _i < _len; _i++) {
      obj = objs[_i];
      for (k in obj) {
        v = obj[k];
        c[k] = v;
      }
    }
    return c;
  };

  ASSET_PATH = path.join(__dirname, '../assets/');

  ENVIRONMENT = extend({}, process.env, {
    'ASSET_PATH': ASSET_PATH
  });

  ENVIRONMENT.PATH = ((_ref = ENVIRONMENT.PATH) != null ? _ref : "") + ":" + NODE_BIN_PATH;

  Builder = (function() {

    function Builder(parameters) {
      this.parameters = parameters;
    }

    Builder.prototype.build = function(target, success, failure) {
      var error_msg, make_argv, make_process,
        _this = this;
      make_argv = ['-f', this.parameters.makefile_path, target];
      ENVIRONMENT.build_path = this.parameters.build_path;
      make_process = child_process.spawn('make', make_argv, {
        env: ENVIRONMENT
      });
      error_msg = "";
      make_process.stderr.on("data", function(data) {
        return error_msg += data.toString();
      });
      return make_process.on('exit', function(code) {
        if (code === 0) {
          return success(target);
        } else {
          _this.onError({
            msg: error_msg,
            target: target
          });
          return failure(error_msg);
        }
      });
    };

    Builder.prototype.onError = function(options) {
      console.log(options.msg);
      return typeof growl === "function" ? growl(options.target + " build failed.") : void 0;
    };

    return Builder;

  })();

  module.exports = Builder;

}).call(this);
