// Generated by CoffeeScript 1.3.3
(function() {
  var default_options, extend, middleware;

  extend = require('./utils').extend;

  default_options = {
    build_path: ".readymade"
  };

  middleware = function(passed_options) {
    var builder, options, server;
    options = extend(default_options, passed_options);
    builder = new Builder({
      makefile_path: options.makefile,
      build_path: options.dest
    });
    server = new Server({
      build_path: options.dest,
      builder: builder
    });
    return function(req, res, next) {
      return server.handle(req, res);
    };
  };

  module.exports = {
    middleware: middleware
  };

}).call(this);
