// Generated by CoffeeScript 1.3.3
(function() {
  var Builder, Server, default_options, extend, middleware;

  extend = require('./utils').extend;

  Builder = require('./builder');

  Server = require('./server');

  default_options = {
    build_path: ".readymade",
    media_root: 'public'
  };

  middleware = function(passed_options) {
    var builder, options, prefix, server;
    options = extend(default_options, passed_options);
    builder = new Builder({
      makefile_path: options.makefile,
      build_path: options.build_path
    });
    prefix = "/" + options.media_root + "/";
    server = new Server({
      build_path: options.build_path,
      builder: builder
    });
    return function(req, res, next) {
      if (req.url.indexOf(prefix) === 0) {
        return server.handle(req, res);
      } else {
        return next();
      }
    };
  };

  module.exports = {
    middleware: middleware
  };

}).call(this);
