// Generated by CoffeeScript 1.3.3
(function() {
  var terminal;

  terminal = require('color-terminal');

  module.exports = {
    URL: {
      attribute: "underline",
      foreground: "blue"
    },
    TARGET: {
      foreground: "black",
      attribute: "bold"
    },
    GET: {
      foreground: "green"
    },
    ERROR: {
      foreground: "red"
    },
    TEXT: {
      foreground: "black"
    }
  };

}).call(this);
