// Generated by CoffeeScript 1.3.3
(function() {
  var ljust, repeat, rjust;

  repeat = function(n, s) {
    if (s == null) {
      s = " ";
    }
    return Array(n + 1).join(s);
  };

  ljust = function(s, n) {
    return repeat(n - s.length) + s;
  };

  rjust = function(s, n) {
    return s + repeat(n - s.length);
  };

  module.exports = {
    ljust: ljust,
    rjust: rjust
  };

}).call(this);
